public class PERCOBAAN1 {
public static void main(String[] args){
    System.out.println("===MENU RESTO CAFE===");
    System.out.println("1. kpi hitam - 15,000");
    System.out.println("2. cappucino - 20,000");
    System.out.println("3. latte - 25,000");
    System.out.println("4. teh tarik - 10,000");
    System.out.println("5. roti bakar - 10,000");
    System.out.println("3. min goreng - 20,000");
    System.out.println("==========================");
    System.out.println("Silahkan pilih menu yang anda inginkan:");
}